[package]
name = "assembler"
version = "0.1.0"
edition = "2021"
authors = ["Anthony Waldsmith <me@anthonyw.me>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jni = "0.21.1"
llvm-sys = "170.0.1"
llvmenv = "0.3.2"
