; Darkmatter LLVM-IR assembly file
;
; NOTE: This file was generated by the Darkmatter compiler.
; Any edits made may not reflect the original source code,
; and may lead to unpredictable results!
;
; Source File:            ${SOURCE_FILE}
; Source Hash:            ${SOURCE_HASH}
; Generated on:           ${TIMESTAMP_HUMAN}
; Compiler:               ${COMPILER_NAME}
; Compiler Version:       ${COMPILER_VERSION_MAJOR}.${COMPILER_VERSION_MINOR}.${COMPILER_VERSION_PATCH}
;
!_DMC_SRC = !"${SOURCE_FILE}"
!_DMC_SRC_HASH = !"${SOURCE_HASH}"
!_DMC_VENDOR = !"${COMPILER_NAME}"
!_DMC_VER = !{!${COMPILER_VERSION_MAJOR}, !${COMPILER_VERSION_MINOR}, !${COMPILER_VERSION_PATCH}}
!_DMC_DAT = !{u64 ${TIMESTAMP_UNIX}}
!_DMC_INT = !{u8 ${ASSEMBLY_INTEGRITY}}
!_DMC_OPT = !{u8 ${COMPILER_OPTIMIZATION}}

